In [1]:
import math

**Square Root**

In [5]:
math.sqrt(100)

10.0

**Power**

In [6]:
math.pow(8,2)

64.0

**Pi**

In [7]:
print(math.pi)

3.141592653589793


**Epsilon**

In [8]:
print(math.e)

2.718281828459045


**Absolute Values**

In [9]:
math.fabs(8)

8.0

**Factorial**

In [2]:
math.factorial(5)

120

**isfinite**

In [11]:
math.isfinite(9)

True

In [14]:
math.isfinite(0.99)

True

**Infinity**

In [17]:
math.isinf(-1.998877)

False

**Isnan**

In [21]:
math.isnan(85)

False

In [24]:
math.remainder(1,2)

1.0

In [ ]:
import math

a = [1,2,3,4,5,6,7,8,9]

b = math.prod(a)

print(b)

In [ ]:
 import math
from math import prod
  
# list 
arr = [1, 2, 3, 4, 5] 
  
# Calculate the product of 
# of all elements present 
# in the given list 
product = math.prod(arr) 
print(product)

In [33]:
import numpy as np

arr = [1, 2, 3, 4, 5]

product = np.prod(arr) 
print(product)

120


In [34]:
array = (1, 2, 3, 4, 5)

product1 = np.prod(array) 
print(product1)

120


In [35]:
seq = range(1, 11)

product2 = np.prod(seq) 
print(product2) 

3628800


**Exponential**

In [27]:
math.exp(2)

7.38905609893065

**Log or Logarithm**

In [28]:
math.log(25)

3.2188758248682006

**Sin/Tan/Cos**

In [36]:
math.sin(5)

-0.9589242746631385

In [37]:
math.tan(5)

-3.380515006246586

In [38]:
math.cos(5)

0.28366218546322625

In [ ]:
math.dist(55,11)

**Angular Conversion**

In [39]:
math.degrees(5)

286.4788975654116

In [41]:
math.radians(286.4788975654116)

5.0

**Program to find sum of an array using Numpy**

In [42]:
import numpy as np

arr = [1, 2, 3, 4, 5]

add = np.sum(arr)
print(add)

15


In [55]:
import numpy as np

array = (1, 2, 3, 4, 5)

add = np.sum(array)
print(add)

15


**Divide using Numpy np.divide()**

In [43]:
import numpy as np
 
# input_array
arr1 = [2, 27, 2, 21, 23]
arr2 = [2, 3, 4, 5, 6]
print ("arr1         : ", arr1)
print ("arr2         : ", arr2)
 
# output_array
out = np.divide(arr1, arr2)
print ("\nOutput array : \n", out)

arr1         :  [2, 27, 2, 21, 23]
arr2         :  [2, 3, 4, 5, 6]

Output array : 
 [1.         9.         0.5        4.2        3.83333333]


**Divide and get remainder as output with np.remainder()**

In [53]:
import numpy as np
 
# input_array
arr1 = [2, 27, 2, 21, 23]
arr2 = [2, 3, 4, 5, 6]

print ("arr1         : ", arr1)
print ("arr2         : ", arr2)

out = np.remainder(arr1, arr2)
print ("\nOutput array : \n", out)

arr1         :  [2, 27, 2, 21, 23]
arr2         :  [2, 3, 4, 5, 6]

Output array : 
 [0 0 2 1 5]


In [46]:
c = np.divide(27,3)
c

9.0

**np.subtract()**

In [47]:
import numpy as np
 
# input_array
arr1 = [2, 27, 2, 21, 23]
arr2 = [2, 3, 4, 5, 6]

print ("arr1         : ", arr1)
print ("arr2         : ", arr2)

out = np.subtract(arr1, arr2)
print ("\nOutput array : \n", out)

arr1         :  [2, 27, 2, 21, 23]
arr2         :  [2, 3, 4, 5, 6]

Output array : 
 [ 0 24 -2 16 17]


**np.multiply()**

In [1]:
%%time

import numpy as np
 
# input_array
arr1 = [2, 27, 2, 21, 23]
arr2 = [2, 3, 4, 5, 6]

print ("arr1         : ", arr1)
print ("arr2         : ", arr2)

out = np.multiply(arr1, arr2)
print ("\nOutput array : \n", out)

arr1         :  [2, 27, 2, 21, 23]
arr2         :  [2, 3, 4, 5, 6]

Output array : 
 [  4  81   8 105 138]
Wall time: 1.79 s


In [50]:
import numpy as np
 
# input_array
arr1 = [2, 27, 2, 21, 23]
arr2 = [2, 3, 4, 5, 6]

print ("arr1         : ", arr1)
print ("arr2         : ", arr2)

out = np.multiply(arr1, arr2)
print ("\nOutput array : \n", out)

arr1         :  [2, 27, 2, 21, 23]
arr2         :  [2, 3, 4, 5, 6]

Output array : 
 [  4  81   8 105 138]


**np.divmod()**

In [2]:
%%time
import numpy as np
 
# input_array
arr1 = [2, 27, 2, 21, 23]
arr2 = [2, 3, 4, 5, 6]

print ("arr1         : ", arr1)
print ("arr2         : ", arr2)

out = np.divmod(arr1, arr2)
print ("\nOutput array : \n", out)

arr1         :  [2, 27, 2, 21, 23]
arr2         :  [2, 3, 4, 5, 6]

Output array : 
 (array([1, 9, 0, 4, 3], dtype=int32), array([0, 0, 2, 1, 5], dtype=int32))
Wall time: 0 ns
